name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: prism
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s
          --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - name: Migrate + seed
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/prism
        run: |
          pnpm migrate
          pnpm seed
          psql "$DATABASE_URL" -f apps/api/db/migrations/0002_fulltext.sql
      - name: Build CLI
        run: pnpm --filter @prism/cli build
      - name: Build API
        run: pnpm --filter @prism/api build
      - name: Run API (background)
        run: pnpm --filter @prism/api dev & sleep 2
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/prism
      - name: FTS smoke
        run: curl -s "http://localhost:3333/api/issues?q=glin:*&limit=2" | jq '.items | length'
      - name: Build Next
        run: pnpm --filter @prism/web-next build
