name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: prism
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s
          --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - name: Migrate + seed
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/prism
        run: |
          pnpm migrate
          pnpm seed
      - name: Build CLI
        run: pnpm --filter @prism/cli build
      - name: Build API
        run: pnpm --filter @prism/api build
      - name: Smoke (placeholder)
        run: node -e "console.log('build ok')"
